// Knowledge base for the PAV·AI RAG — Pavani Rajula's resume, chunked.
// Each chunk is one retrievable passage. Keep them short and self-contained:
// retrieval quality depends on each chunk making sense on its own.
export const CHUNKS = [
  "Pavani Rajula is an AI Developer and Data Scientist. She architects agentic AI systems — LLMs, RAG pipelines, tool orchestration, and MCP frameworks — embedded with client teams from architecture through deployment. Her tagline: from prompt to production.",
  "Pavani holds an MSc in Data Science from the University of Mannheim, Germany (2022–2024), completed alongside full-time AI work. Her thesis, PIP-Net Fusion, covered interpretable model ensembling and federation.",
  "Pavani earned a B.Tech in Information Technology from BVRIT Hyderabad College of Engineering for Women (2015–2019), covering algorithms, machine learning, big data analytics, cloud computing, databases, and software engineering.",
  "Since September 2025, Pavani is a Data Science & AI Developer at NeuCorelytix Solutions LLP (remote), working as an external consultant to Data Migration International. She architects agentic AI systems: LLMs, RAG, tool orchestration, and autonomous workflows.",
  "At NeuCorelytix, Pavani designs scalable AI services using microservices, async pipelines, and distributed execution with optimized inference. She implements vector databases for retrieval-augmented workflows and semantic search, and builds MCP frameworks for evaluation metrics, hallucination mitigation, monitoring, and feedback loops.",
  "From October 2023 to September 2025, Pavani was a Data Science & AI Developer at Data Migration International in Kreuzlingen, Switzerland. She shipped production LLM, RAG, and NLP solutions with end-to-end ML pipelines, and led AI integration including conversational agents, GDPR-compliant PII identification, and data-quality systems.",
  "From July 2019 to February 2022, Pavani was an Associate 2 Data Engineer at State Street Corporation in Hyderabad, India. She owned six regulatory reports on Axiom Controller View across the full SDLC, automated reporting with SQL/UNIX/shell for a 40% reduction in manual workload, and ran Python over 20 TB of Hadoop data for 50% faster processing. An AWS migration proof of concept cut infrastructure cost by 30%.",
  "From May to August 2018, Pavani was an Outreachy open-source intern at the Ceph Organization (remote). She built the CephFS Shell — Unix-style commands over libcephfs Python bindings — plus documentation, which is still in the official Ceph docs.",
  "Project — AI Business Incorporation & Compliance Platform (agentic, RAG): founders drown in dense legal PDFs when checking incorporation eligibility and compliance. Pavani built a headless multi-channel platform in a Turborepo monorepo with type-safe NestJS APIs plus a standalone Python RAG service using local embeddings and vector search over legal corpora. Outcome: self-serve compliance checks where founders query complex regulation in plain language. Stack: FastAPI, Qdrant, Next.js, NestJS, Prisma, Turborepo. It is proprietary client work.",
  "Project — PIP-Net Fusion (MSc thesis): ensembles boost accuracy but usually destroy interpretability, a dealbreaker in high-stakes ML. Pavani fused multiple interpretable PIP-Net models via ensembling and federation strategies, preserving prototype-based transparency, achieving higher accuracy without sacrificing explainability. It was extended as a poster at PyTorch Conference Europe 2026. Stack: PyTorch, XAI, Federated Learning, Computer Vision.",
  "Project — Decoding Word Embeddings (NLP research): embeddings are powerful but opaque. Pavani extended SensePOLAR to support multiple oracles, models, and languages, with a Streamlit interface for rapid experiments, producing a reusable interpretability tool. Stack: Hugging Face, Streamlit, word embeddings, Python.",
  "Project — Water Damage Detection (Datathon 2023): identifying water damage in property images is slow and inconsistent. Pavani used U-Net segmentation with transfer-learning feature engineering for pixel-precise localization, delivering a robust detection pipeline under competition constraints.",
  "Pavani's skills in LLM & Agentic Engineering: Agentic AI, RAG, MCP, tool orchestration, prompt engineering, LangChain, LlamaIndex, Agno, OpenAI API, Hugging Face Transformers, and semantic search.",
  "Pavani's skills in Evaluation & Reliability: LLM eval metrics, hallucination mitigation, monitoring, feedback loops, MLflow, and inference optimization.",
  "Pavani's skills in Client Delivery & Solutions: client-embedded consulting, turning requirements into production, rapid prototyping, end-to-end ownership, GDPR and compliance domains, demos and technical talks, and cross-functional delivery.",
  "Pavani's skills in ML and Deep Learning: PyTorch, TensorFlow, scikit-learn, computer vision, NLP, reinforcement learning, and explainable AI.",
  "Pavani's skills in Backend & APIs: Python, FastAPI, NestJS, REST APIs, microservices, async pipelines, Celery, Redis, Java, and SQL.",
  "Pavani's skills in Data & Retrieval Infrastructure: Qdrant, vector search, embeddings, MongoDB, MySQL, Hive, Hadoop, and Spark.",
  "Pavani's skills in Cloud & MLOps: Docker, AWS (S3, Lambda, IAM), Azure, distributed task execution, and UNIX/shell. Frontend and prototyping: Next.js, React, Streamlit, Node.js, Turborepo.",
  "Recognition — Pavani won the JIVS Hackathon 'All About Data & AI' at Data Migration International with a Geo-Masking privacy system that prevents identification of people and locations in shared images.",
  "Recognition — Pavani published in the CLEF 2022 Working Notes: 'Stacked Model based Argument Extraction and Stance Detection using Embedded LSTM', with a conference talk. She also has a poster at PyTorch Conference Europe 2026: 'When Models Collaborate but Data Cannot: Explainable Ensemble Learning Under Privacy Constraints.'",
  "Recognition — Pavani received 3 Linux Foundation scholarships (Open Source Summit EU 2022, KubeCon EU 2020 and 2022) for sustained open-source and cloud-native contributions. She spoke at DevConf.in Bengaluru (Ceph) and PyConf Hyderabad ('Open Source for Beginners') in 2019, and was a 2018 Outreachy participant via the Software Freedom Conservancy.",
  "Pavani writes on Substack about agentic systems, RAG in production, evals, hallucination mitigation, and lessons from client-embedded AI work. Read at pavanirajula.substack.com.",
  "Why Pavani stands out: she works embedded inside a client's environment today, turning requirements into production systems; she owns the full AI delivery stack (RAG services, evals, hallucination mitigation, APIs, deployment); she is client-facing with conference talks, demos, and hackathon wins; and she has domain depth in GDPR and compliance, regulated environments where reliability matters most.",
  "Contact — email rajulapavani@outlook.com, LinkedIn linkedin.com/in/rajula-pavani, GitHub github.com/rpavani1998, Substack pavanirajula.substack.com. Pavani is based in Hyderabad, India, is remote-friendly, and is open to AI engineering opportunities.",
  "Pavani's languages: English (C1), German (A1), Telugu, and Hindi. Outside work she enjoys singing, yoga, badminton, and art.",
  "RAG and agents are Pavani's specialty: Qdrant vector search with local embeddings, multi-tool agent orchestration, and MCP frameworks for evaluation, hallucination mitigation, and production monitoring."
];
